# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class MyMainWindow(object):
    def setupUi(self, MyMainWindow):
        MyMainWindow.setObjectName("MyMainWindow")
        MyMainWindow.setWindowModality(QtCore.Qt.NonModal)
        MyMainWindow.setEnabled(True)
        MyMainWindow.resize(1283, 896)
        MyMainWindow.setMinimumSize(QtCore.QSize(1283, 896))
        MyMainWindow.setMaximumSize(QtCore.QSize(1283, 896))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        MyMainWindow.setFont(font)
        MyMainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MyMainWindow.setAutoFillBackground(False)
        MyMainWindow.setStyleSheet("#centralwidget {background-image: url(\"D:/lg/BaiduSyncdisk/project/person_code/project_self/pyqt/det/icon/background.jpg\");}\n"
"\n"
"")
        MyMainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.China))
        self.centralwidget = QtWidgets.QWidget(MyMainWindow)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setGeometry(QtCore.QRect(120, 12, 1011, 71))
        self.label_title.setMinimumSize(QtCore.QSize(0, 0))
        self.label_title.setMaximumSize(QtCore.QSize(10000, 10000))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("color: rgb(50, 50, 50);  /* 深炭灰（替代纯黑） */\n"
"font: 30pt \"黑体\";\n"
"text-shadow: 1px 1px 3px rgba(200, 200, 200, 0.3);  /* 微阴影增强层次 */\n"
"background: linear-gradient(to right, \n"
"    rgba(240,240,240,0.8), \n"
"    rgba(220,220,220,0.9));  /* 浅灰渐变背景 */\n"
"border-radius: 4px;\n"
"padding: 8px 12px;\n"
"border-left: 4px solid rgb(180,180,180);  /* 左侧装饰线 */")
        self.label_title.setScaledContents(True)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(257, 90, 721, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.frame.setFont(font)
        self.frame.setAcceptDrops(True)
        self.frame.setToolTipDuration(-2)
        self.frame.setFrameShape(QtWidgets.QFrame.HLine)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(1)
        self.frame.setObjectName("frame")
        self.label_img = QtWidgets.QLabel(self.centralwidget)
        self.label_img.setGeometry(QtCore.QRect(380, 210, 891, 441))
        self.label_img.setStyleSheet("background-color: rgba(122, 135, 154, 150);\n"
"border-radius: 15px;\n"
"")
        self.label_img.setText("")
        self.label_img.setPixmap(QtGui.QPixmap("icon/zhutu2.png"))
        self.label_img.setAlignment(QtCore.Qt.AlignCenter)
        self.label_img.setWordWrap(False)
        self.label_img.setIndent(-1)
        self.label_img.setOpenExternalLinks(False)
        self.label_img.setObjectName("label_img")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(250, 197, 50, 27))
        self.label_23.setText("")
        self.label_23.setPixmap(QtGui.QPixmap("icon2/mubiaojiance.png"))
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(260, 240, 30, 30))
        self.label_24.setText("")
        self.label_24.setPixmap(QtGui.QPixmap("icon2/mubiaogenzong.png"))
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.label_classes = QtWidgets.QLabel(self.centralwidget)
        self.label_classes.setGeometry(QtCore.QRect(800, 690, 41, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(13)
        self.label_classes.setFont(font)
        self.label_classes.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_classes.setText("")
        self.label_classes.setObjectName("label_classes")
        self.tableWidget_info = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_info.setGeometry(QtCore.QRect(380, 670, 891, 171))
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.tableWidget_info.setFont(font)
        self.tableWidget_info.setStyleSheet("QHeaderView::section {\n"
"    background-color: rgb(56, 128, 56);  /* 深绿色标题 */\n"
"    color: white;\n"
"    border: 1px solid #3d7a3d;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    background-color: rgb(34, 72, 50);    /* 墨绿色背景 */\n"
"    color: #e0e0e0;                       /* 浅灰色文字 */\n"
"    gridline-color: #456d4f;\n"
"}\n"
"\n"
"QTableView::item:hover {\n"
"    background-color: rgb(120, 190, 120);  /* 柔和的草绿色悬停效果 */\n"
"    color: black;\n"
"}\n"
"\n"
"QTableView::item:selected:!active {\n"
"    background-color: #e8f5e9;            /* 薄荷绿选中状态 */\n"
"    color: #2e7d32;\n"
"}")
        self.tableWidget_info.setLineWidth(0)
        self.tableWidget_info.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_info.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_info.setAutoScroll(False)
        self.tableWidget_info.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_info.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_info.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_info.setShowGrid(True)
        self.tableWidget_info.setGridStyle(QtCore.Qt.CustomDashLine)
        self.tableWidget_info.setWordWrap(True)
        self.tableWidget_info.setCornerButtonEnabled(True)
        self.tableWidget_info.setRowCount(6)
        self.tableWidget_info.setColumnCount(7)
        self.tableWidget_info.setObjectName("tableWidget_info")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_info.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_info.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_info.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_info.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_info.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_info.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_info.setHorizontalHeaderItem(6, item)
        self.tableWidget_info.horizontalHeader().setVisible(True)
        self.tableWidget_info.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_info.horizontalHeader().setDefaultSectionSize(128)
        self.tableWidget_info.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget_info.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_info.verticalHeader().setVisible(False)
        self.tableWidget_info.verticalHeader().setCascadingSectionResizes(False)
        self.label_info = QtWidgets.QLabel(self.centralwidget)
        self.label_info.setGeometry(QtCore.QRect(140, 117, 951, 21))
        self.label_info.setScaledContents(True)
        self.label_info.setAlignment(QtCore.Qt.AlignCenter)
        self.label_info.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_info.setObjectName("label_info")
        self.label_img_path = QtWidgets.QLabel(self.centralwidget)
        self.label_img_path.setGeometry(QtCore.QRect(90, 162, 221, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        self.label_img_path.setFont(font)
        self.label_img_path.setToolTipDuration(-1)
        self.label_img_path.setStyleSheet("background-color: rgba(255, 255, 255, 0.1); /* 30%透明度的白色 */\n"
"font: 11pt \"黑体\";\n"
"border-radius: 7px;")
        self.label_img_path.setTextFormat(QtCore.Qt.AutoText)
        self.label_img_path.setObjectName("label_img_path")
        self.label_video_path = QtWidgets.QLabel(self.centralwidget)
        self.label_video_path.setGeometry(QtCore.QRect(770, 162, 221, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        self.label_video_path.setFont(font)
        self.label_video_path.setToolTipDuration(-1)
        self.label_video_path.setStyleSheet("background-color: rgba(255, 255, 255, 0.1); /* 白色，30%透明度 */\n"
"font: 11pt \"黑体\";\n"
"border-radius: 7px;")
        self.label_video_path.setTextFormat(QtCore.Qt.AutoText)
        self.label_video_path.setObjectName("label_video_path")
        self.pushButton_img = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_img.setGeometry(QtCore.QRect(30, 152, 45, 45))
        self.pushButton_img.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border-radius: 10px; /* 设置圆角半径为10像素 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(98, 105, 111);\n"
"}")
        self.pushButton_img.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/dirs.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_img.setIcon(icon)
        self.pushButton_img.setIconSize(QtCore.QSize(40, 27))
        self.pushButton_img.setObjectName("pushButton_img")
        self.pushButton_video = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_video.setGeometry(QtCore.QRect(710, 155, 45, 45))
        self.pushButton_video.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border-radius: 10px; /* 设置圆角半径为10像素 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(98, 105, 111);\n"
"}")
        self.pushButton_video.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/shipinwenjian.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_video.setIcon(icon1)
        self.pushButton_video.setIconSize(QtCore.QSize(40, 27))
        self.pushButton_video.setObjectName("pushButton_video")
        self.pushButton_dir = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_dir.setGeometry(QtCore.QRect(360, 152, 45, 45))
        self.pushButton_dir.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border-radius: 10px; /* 设置圆角半径为10像素 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(98, 105, 111);\n"
"}")
        self.pushButton_dir.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon/dir.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_dir.setIcon(icon2)
        self.pushButton_dir.setIconSize(QtCore.QSize(40, 27))
        self.pushButton_dir.setObjectName("pushButton_dir")
        self.label_dir_path = QtWidgets.QLabel(self.centralwidget)
        self.label_dir_path.setGeometry(QtCore.QRect(420, 160, 221, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        self.label_dir_path.setFont(font)
        self.label_dir_path.setToolTipDuration(-1)
        self.label_dir_path.setStyleSheet("background-color: rgba(255, 255, 255, 0.1); /* 白色，30%透明度 */\n"
"font: 11pt \"黑体\";\n"
"border-radius: 7px;")
        self.label_dir_path.setTextFormat(QtCore.Qt.AutoText)
        self.label_dir_path.setObjectName("label_dir_path")
        self.location = QtWidgets.QLabel(self.centralwidget)
        self.location.setGeometry(QtCore.QRect(30, 674, 30, 30))
        self.location.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border-radius: 10px; /* 设置圆角半径为10像素 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(98, 105, 111);\n"
"}")
        self.location.setText("")
        self.location.setPixmap(QtGui.QPixmap("icon/weizhi.png"))
        self.location.setAlignment(QtCore.Qt.AlignCenter)
        self.location.setObjectName("location")
        self.confidence = QtWidgets.QLabel(self.centralwidget)
        self.confidence.setGeometry(QtCore.QRect(30, 540, 29, 34))
        self.confidence.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border-radius: 10px; /* 设置圆角半径为10像素 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(98, 105, 111);\n"
"}")
        self.confidence.setText("")
        self.confidence.setPixmap(QtGui.QPixmap("icon/zhixindu.png"))
        self.confidence.setAlignment(QtCore.Qt.AlignCenter)
        self.confidence.setObjectName("confidence")
        self.splitline3 = QtWidgets.QFrame(self.centralwidget)
        self.splitline3.setGeometry(QtCore.QRect(20, 440, 301, 27))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        self.splitline3.setFont(font)
        self.splitline3.setStyleSheet("QFrame {\n"
"    border: none;\n"
"    background-color: rgba(34, 139, 34, 0.3);  /* 半透明森林绿 */\n"
"    min-height: 3px;\n"
"    max-height: 3px;\n"
"    margin: 12px 0;\n"
"    border-radius: 2px;\n"
"}")
        self.splitline3.setFrameShape(QtWidgets.QFrame.HLine)
        self.splitline3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.splitline3.setLineWidth(1)
        self.splitline3.setMidLineWidth(0)
        self.splitline3.setObjectName("splitline3")
        self.label_control = QtWidgets.QLabel(self.centralwidget)
        self.label_control.setGeometry(QtCore.QRect(10, 210, 351, 631))
        self.label_control.setStyleSheet("background-color: rgba(122, 135, 154, 100);\n"
"border-radius: 15px;\n"
"")
        self.label_control.setText("")
        self.label_control.setObjectName("label_control")
        self.pushButton_start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start.setGeometry(QtCore.QRect(100, 300, 141, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        self.pushButton_start.setFont(font)
        self.pushButton_start.setStyleSheet("background-color: rgb(52,128,56);\n"
"font: 11pt \"黑体\";\n"
"\n"
"border-radius: 15px;\n"
"\n"
"color: rgb(255, 255, 255);")
        self.pushButton_start.setObjectName("pushButton_start")
        self.label_accuracy_value_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_accuracy_value_2.setGeometry(QtCore.QRect(30, 610, 29, 34))
        self.label_accuracy_value_2.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border-radius: 10px; /* 设置圆角半径为10像素 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(98, 105, 111);\n"
"}")
        self.label_accuracy_value_2.setText("")
        self.label_accuracy_value_2.setPixmap(QtGui.QPixmap("icon/accuracy.png"))
        self.label_accuracy_value_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_accuracy_value_2.setObjectName("label_accuracy_value_2")
        self.classes = QtWidgets.QLabel(self.centralwidget)
        self.classes.setGeometry(QtCore.QRect(30, 475, 30, 30))
        self.classes.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border-radius: 10px; /* 设置圆角半径为10像素 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(98, 105, 111);\n"
"}")
        self.classes.setText("")
        self.classes.setPixmap(QtGui.QPixmap("icon/leibie.png"))
        self.classes.setAlignment(QtCore.Qt.AlignCenter)
        self.classes.setObjectName("classes")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(80, 240, 221, 31))
        self.comboBox.setStyleSheet("QComboBox {\n"
"    background-color: rgb(70, 80, 90);  /* 深蓝灰色背景 */\n"
"    color: rgb(200, 210, 220);         /* 浅灰蓝色文字 */\n"
"    font-size: 17px;\n"
"    border: 1px solid rgb(50, 60, 70); /* 边框颜色与背景协调 */\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.label_xmax_v = QtWidgets.QLabel(self.centralwidget)
        self.label_xmax_v.setGeometry(QtCore.QRect(120, 780, 51, 27))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        self.label_xmax_v.setFont(font)
        self.label_xmax_v.setStyleSheet("font: 11pt \"Arial\";")
        self.label_xmax_v.setObjectName("label_xmax_v")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(70, 480, 111, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("font: 11pt \"黑体\";")
        self.label_7.setObjectName("label_7")
        self.label_ymax_v = QtWidgets.QLabel(self.centralwidget)
        self.label_ymax_v.setGeometry(QtCore.QRect(290, 780, 51, 27))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        self.label_ymax_v.setFont(font)
        self.label_ymax_v.setStyleSheet("font: 11pt \"Arial\";")
        self.label_ymax_v.setObjectName("label_ymax_v")
        self.label_xmin = QtWidgets.QLabel(self.centralwidget)
        self.label_xmin.setGeometry(QtCore.QRect(30, 730, 71, 27))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        self.label_xmin.setFont(font)
        self.label_xmin.setStyleSheet("font: 11pt \"Arial\";")
        self.label_xmin.setObjectName("label_xmin")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(69, 615, 111, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("font: 11pt \"黑体\";")
        self.label_8.setObjectName("label_8")
        self.ymax = QtWidgets.QLabel(self.centralwidget)
        self.ymax.setGeometry(QtCore.QRect(200, 780, 71, 27))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        self.ymax.setFont(font)
        self.ymax.setStyleSheet("font: 11pt \"Arial\";")
        self.ymax.setObjectName("ymax")
        self.label_score = QtWidgets.QLabel(self.centralwidget)
        self.label_score.setGeometry(QtCore.QRect(140, 550, 171, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        self.label_score.setFont(font)
        self.label_score.setStyleSheet("font: 11pt \"黑体\";")
        self.label_score.setText("")
        self.label_score.setAlignment(QtCore.Qt.AlignCenter)
        self.label_score.setObjectName("label_score")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(69, 545, 111, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("font: 11pt \"黑体\";")
        self.label_6.setObjectName("label_6")
        self.location2 = QtWidgets.QLabel(self.centralwidget)
        self.location2.setGeometry(QtCore.QRect(70, 680, 111, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        self.location2.setFont(font)
        self.location2.setStyleSheet("font: 11pt \"黑体\";")
        self.location2.setObjectName("location2")
        self.search = QtWidgets.QLabel(self.centralwidget)
        self.search.setGeometry(QtCore.QRect(30, 240, 30, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        self.search.setFont(font)
        self.search.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border-radius: 10px; /* 设置圆角半径为10像素 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(98, 105, 111);\n"
"}")
        self.search.setText("")
        self.search.setPixmap(QtGui.QPixmap("icon/suoyoumubiao.png"))
        self.search.setAlignment(QtCore.Qt.AlignCenter)
        self.search.setObjectName("search")
        self.ymin = QtWidgets.QLabel(self.centralwidget)
        self.ymin.setGeometry(QtCore.QRect(200, 730, 71, 27))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        self.ymin.setFont(font)
        self.ymin.setStyleSheet("font: 11pt \"Arial\";")
        self.ymin.setObjectName("ymin")
        self.pushButton_export = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_export.setGeometry(QtCore.QRect(100, 380, 141, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        self.pushButton_export.setFont(font)
        self.pushButton_export.setStyleSheet("background-color: rgb(52,128,56);\n"
"font: 11pt \"黑体\";\n"
"\n"
"border-radius: 15px;\n"
"\n"
"color: rgb(255, 255, 255);")
        self.pushButton_export.setObjectName("pushButton_export")
        self.label_ymin_v = QtWidgets.QLabel(self.centralwidget)
        self.label_ymin_v.setGeometry(QtCore.QRect(290, 730, 51, 27))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        self.label_ymin_v.setFont(font)
        self.label_ymin_v.setStyleSheet("font: 11pt \"Arial\";")
        self.label_ymin_v.setObjectName("label_ymin_v")
        self.label_xmin_v = QtWidgets.QLabel(self.centralwidget)
        self.label_xmin_v.setGeometry(QtCore.QRect(120, 730, 51, 27))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        self.label_xmin_v.setFont(font)
        self.label_xmin_v.setStyleSheet("font: 11pt \"Arial\";")
        self.label_xmin_v.setObjectName("label_xmin_v")
        self.label_class = QtWidgets.QLabel(self.centralwidget)
        self.label_class.setGeometry(QtCore.QRect(140, 480, 171, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        self.label_class.setFont(font)
        self.label_class.setStyleSheet("font: 11pt \"黑体\";")
        self.label_class.setText("")
        self.label_class.setAlignment(QtCore.Qt.AlignCenter)
        self.label_class.setObjectName("label_class")
        self.label_accuracy_value = QtWidgets.QLabel(self.centralwidget)
        self.label_accuracy_value.setGeometry(QtCore.QRect(140, 620, 171, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        self.label_accuracy_value.setFont(font)
        self.label_accuracy_value.setStyleSheet("font: 11pt \"黑体\";")
        self.label_accuracy_value.setText("")
        self.label_accuracy_value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_accuracy_value.setObjectName("label_accuracy_value")
        self.xmax = QtWidgets.QLabel(self.centralwidget)
        self.xmax.setGeometry(QtCore.QRect(30, 780, 71, 27))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        self.xmax.setFont(font)
        self.xmax.setStyleSheet("font: 11pt \"Arial\";")
        self.xmax.setObjectName("xmax")
        self.pushButton_camera = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_camera.setGeometry(QtCore.QRect(980, 150, 45, 45))
        self.pushButton_camera.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border-radius: 10px; /* 设置圆角半径为10像素 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(98, 105, 111);\n"
"}")
        self.pushButton_camera.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icon/shexiangtou.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_camera.setIcon(icon3)
        self.pushButton_camera.setIconSize(QtCore.QSize(40, 27))
        self.pushButton_camera.setObjectName("pushButton_camera")
        self.label_camera_path = QtWidgets.QLabel(self.centralwidget)
        self.label_camera_path.setGeometry(QtCore.QRect(1040, 160, 221, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        font.setBold(False)
        self.label_camera_path.setFont(font)
        self.label_camera_path.setToolTipDuration(-1)
        self.label_camera_path.setStyleSheet("background-color: rgba(255, 255, 255, 50);\n"
"\n"
"border-radius: 7px;\n"
"\n"
"")
        self.label_camera_path.setTextFormat(QtCore.Qt.AutoText)
        self.label_camera_path.setObjectName("label_camera_path")
        MyMainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MyMainWindow)
        QtCore.QMetaObject.connectSlotsByName(MyMainWindow)

    def retranslateUi(self, MyMainWindow):
        _translate = QtCore.QCoreApplication.translate
        MyMainWindow.setWindowTitle(_translate("MyMainWindow", "水果图像识别与分类系统"))
        MyMainWindow.setProperty("setWindowFlags", _translate("MyMainWindow", "QtCore.Qt.FramelessWindowHint"))
        MyMainWindow.setProperty("setAttribute", _translate("MyMainWindow", "QtCore.Qt.WA_TranslucentBackground"))
        self.label_title.setText(_translate("MyMainWindow", "YOLOv8s水果图像分类系统"))
        self.tableWidget_info.setSortingEnabled(False)
        self.tableWidget_info.setProperty("sectionResizeMode", _translate("MyMainWindow", "QHeaderView::ResizeToContents"))
        item = self.tableWidget_info.horizontalHeaderItem(0)
        item.setText(_translate("MyMainWindow", "序号"))
        item = self.tableWidget_info.horizontalHeaderItem(1)
        item.setText(_translate("MyMainWindow", "文件名称"))
        item = self.tableWidget_info.horizontalHeaderItem(2)
        item.setText(_translate("MyMainWindow", "上传时间"))
        item = self.tableWidget_info.horizontalHeaderItem(3)
        item.setText(_translate("MyMainWindow", "检测结果"))
        item = self.tableWidget_info.horizontalHeaderItem(4)
        item.setText(_translate("MyMainWindow", "目标数量"))
        item = self.tableWidget_info.horizontalHeaderItem(5)
        item.setText(_translate("MyMainWindow", "计算耗时"))
        item = self.tableWidget_info.horizontalHeaderItem(6)
        item.setText(_translate("MyMainWindow", "存储位置"))
        self.label_info.setText(_translate("MyMainWindow", "姓名: 许悦                                         专业：数据科学与大数据技术                                            学号：212090623"))
        self.label_img_path.setText(_translate("MyMainWindow", " 选择图片文件"))
        self.label_video_path.setText(_translate("MyMainWindow", "选择视频文件"))
        self.label_dir_path.setText(_translate("MyMainWindow", "批量上传图片"))
        self.pushButton_start.setText(_translate("MyMainWindow", "启动检测 ▶"))
        self.comboBox.setItemText(0, _translate("MyMainWindow", "所有目标"))
        self.label_xmax_v.setText(_translate("MyMainWindow", "0"))
        self.label_7.setText(_translate("MyMainWindow", "类别:"))
        self.label_ymax_v.setText(_translate("MyMainWindow", "0"))
        self.label_xmin.setText(_translate("MyMainWindow", "xcenter:"))
        self.label_8.setText(_translate("MyMainWindow", "准确率:"))
        self.ymax.setText(_translate("MyMainWindow", "weight:"))
        self.label_6.setText(_translate("MyMainWindow", "置信度:"))
        self.location2.setText(_translate("MyMainWindow", "位置:"))
        self.ymin.setText(_translate("MyMainWindow", "ycenter:"))
        self.pushButton_export.setText(_translate("MyMainWindow", "生成报告 ▶"))
        self.label_ymin_v.setText(_translate("MyMainWindow", "0"))
        self.label_xmin_v.setText(_translate("MyMainWindow", "0"))
        self.xmax.setText(_translate("MyMainWindow", "width:"))
        self.label_camera_path.setText(_translate("MyMainWindow", " 启用实时摄像头"))
